name: $(version)

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:

- name: buildConfiguration
  value: 'Release'
- name: version
  value: $[format('5.0.{0}', counter('5.0', 0))]

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.101'
  inputs:
    packageType: sdk
    version: 3.1.101
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      **/*.json

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet test'
#  inputs:
#    command: test
#    projects: '**/*Tests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: 'SW.Bus/SW.Bus.csproj;'
    nobuild: true
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'swnuget' 
